# Generated by Django 5.2.7 on 2025-10-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
