# Generated by Django 5.2.7 on 2025-10-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_quantity"),
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
